**Single Layer Perceptron - AND or OR Gate**

In [14]:
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])

In [15]:
class Perceptron:
    def __init__(self, learning_rate=0.1, num_iterations=100):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
        self.weights = np.zeros((2, 1))
        self.bias = 0

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_output)

    def train(self, X, y):
        for _ in range(self.num_iterations):
            predictions = self.predict(X)
            error = y - predictions
            self.weights += self.learning_rate * np.dot(X.T, error)
            self.bias += self.learning_rate * np.sum(error)

In [16]:
# Train the perceptron
perceptron = Perceptron()
perceptron.train(X, y)

In [17]:
# Test the perceptron
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_outputs = perceptron.predict(test_inputs)
print("Test Outputs:")
print(test_outputs)

Test Outputs:
[[0.05104813]
 [0.23731845]
 [0.23731845]
 [0.64284042]]


In [18]:
#For OR GATE
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])

In [19]:
perceptron = Perceptron()
perceptron.train(X, y)

In [20]:
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_outputs = perceptron.predict(test_inputs)
print("Test Outputs:")
print(test_outputs)

Test Outputs:
[[0.35735642]
 [0.87190274]
 [0.87190274]
 [0.98813976]]


**Back Propagation - XOR Gate**

In [9]:
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [10]:
class NeuralNetwork:
    def __init__(self, input_dim, hidden_dim, output_dim):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.weights1 = np.random.rand(input_dim, hidden_dim)
        self.weights2 = np.random.rand(hidden_dim, output_dim)
        self.bias1 = np.zeros((1, hidden_dim))
        self.bias2 = np.zeros((1, output_dim))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward_pass(self, X):
        hidden_layer = self.sigmoid(np.dot(X, self.weights1) + self.bias1)
        output_layer = self.sigmoid(np.dot(hidden_layer, self.weights2) + self.bias2)
        return hidden_layer, output_layer

    def backward_pass(self, X, y, hidden_layer, output_layer):
        output_error = y - output_layer
        output_delta = output_error * self.sigmoid_derivative(output_layer)

        hidden_error = output_delta.dot(self.weights2.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(hidden_layer)

        self.weights2 += 0.1 * hidden_layer.T.dot(output_delta)
        self.bias2 += 0.1 * np.sum(output_delta, axis=0, keepdims=True)

        self.weights1 += 0.1 * X.T.dot(hidden_delta)
        self.bias1 += 0.1 * np.sum(hidden_delta, axis=0, keepdims=True)

    def train(self, X, y, num_iterations):
        for _ in range(num_iterations):
            hidden_layer, output_layer = self.forward_pass(X)
            self.backward_pass(X, y, hidden_layer, output_layer)

    def predict(self, X):
        _, output_layer = self.forward_pass(X)
        return output_layer

In [11]:
nn = NeuralNetwork(2, 2, 1)
nn.train(X, y, 10000)

In [12]:
test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
test_outputs = nn.predict(test_inputs)
print("Test Outputs:")
print(test_outputs)

Test Outputs:
[[0.05202613]
 [0.95279468]
 [0.95266863]
 [0.05059031]]
